# -*- coding: utf-8 -*-
"""iris_reg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15_MEKRkGrZK4q72ycx0H-4avzJMFhiDJ
"""

import numpy as np #linear algebra
import pandas as pd # a data processing and CSV I/O library

class Context:
  DATA = 'https://raw.githubusercontent.com/jfogarty/machine-learning-intro-workshop/master/data/'

URL = Context.DATA + 'Iris.csv'
iris = pd.read_csv(URL)

print(iris.head(10))

iris=iris.drop('Id', axis=1)

from sklearn.preprocessing import OrdinalEncoder

ord_enc = OrdinalEncoder()

iris["species_code"] = ord_enc.fit_transform(iris[["Species"]])

from sklearn.linear_model import LogisticRegression as lr

X=iris.iloc[:, :4]

X.describe()

X=X.to_numpy()

y=iris["species_code"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

model = lr(max_iter=1500)
model.fit(X_train, y_train)

y_pred=model.predict(X_test)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

print(model.score(X_test,y_test))

print('Введите значения SepalLengthCm(5-8 см),	SepalWidthCm(2-4.5 см),	PetalLengthCm(1-7см),	PetalWidthCm(0.1-2.5см), через пробел')
a=list(map(float, input().split()))

x=np.array(a)

x=x.reshape(1, -1)

y_1=model.predict(x)
y_1

print('Вид Ириса: ', ord_enc.inverse_transform(y_1.reshape(1, -1))[0,0])

